stages:
  - test

test:sanity-devel-py38:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/shippable/sanity.sh sanity/1
    - bash tests/utils/shippable/sanity.sh sanity/2
    - bash tests/utils/shippable/sanity.sh sanity/3
    - bash tests/utils/shippable/sanity.sh sanity/4
  tags:
    - hc-bladerunner

test:integration-devel-py38:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py39-$CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner


test:integration-devel-py39:
  stage: test
  image: python:3.9-rc-buster
  allow_failure: true
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py39-$CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner
