stages:
  - test

test:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - cat "$(pwd)/hcloud_token.txt"
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner
