stages:
  - test

test:integration-ansible-devel-py-38:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py39-CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner


test:integration-ansible-devel-py-39:
  stage: test
  image: python:3.9-rc-buster
  allow_failure: true
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py39-CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner
