stages:
  - test

test:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo $HCLOUD_TOKEN >> hcloud_token.txt
    - cat hcloud_token.txt
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner
