stages:
  - test

test:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - export HCLOUD_TOKEN=$HCLOUD_TOKEN
    - bash tests/utils/gitlab/gitlab.sh
  tags:
    - hc-bladerunner
