stages:
  - sanity
  - integration

test:sanity1-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity/1
  tags:
    - hc-bladerunner

test:sanity2-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity/2
  tags:
    - hc-bladerunner

test:sanity3-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity/3
  tags:
    - hc-bladerunner

test:sanity4-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity/4
  tags:
    - hc-bladerunner

test:integration1-devel-py38:
  stage: integration
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py38-$CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh integration/1
  tags:
    - hc-bladerunner


test:integration2-devel-py38:
  stage: integration
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py39-$CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh integration/2
  tags:
    - hc-bladerunner
