stages:
  - sanity
  - test

test:sanity1-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity sanity/1
  tags:
    - hc-bladerunner

test:sanity2-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity sanity/2
  tags:
    - hc-bladerunner

test:sanity3-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity sanity/3
  tags:
    - hc-bladerunner

test:sanity4-devel-py38:
  stage: sanity
  image: python:3.8-buster
  except:
    - tags
  script:
    - bash tests/utils/gitlab/gitlab.sh sanity sanity/4
  tags:
    - hc-bladerunner

test:integration-devel-py38:
  stage: test
  image: python:3.8-buster
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py38-$CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh integration
  tags:
    - hc-bladerunner


test:integration-devel-py39:
  stage: test
  image: python:3.9-rc-buster
  allow_failure: true
  except:
    - tags
  script:
    - echo "$HCLOUD_TOKEN" >> "$(pwd)/hcloud_token.txt"
    - echo "py39-$CI_JOB_ID" >> "$(pwd)/prefix.txt"
    - bash tests/utils/gitlab/gitlab.sh integration
  tags:
    - hc-bladerunner
